### ISSUE TITLE
Replace CommandLog

### ISSUE THREAD

**Issue by MilesBHuff** [SettleScape/server#37]
The CommandLog plugin is ancient -- it hasn't been updated since 2016!  We need to find a replacement in case CommandLog ever becomes incompatible with modern Minecraft or in case it contains an unpatched security flaw.

**Comment by MilesBHuff** [comment]
I finally found a suitable replacement:  https://www.spigotmc.org/resources/commandspy-1-7-1-14.27132

**Comment by MilesBHuff** [comment]
`[02:25:49 INFO]: [CommandSpy] Enabling CommandSpy v1.4*
[02:25:49 INFO]: [CommandSpy]: Failed to connect to metrics service
[02:25:49 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://metrics.joshuahagon.co.uk/?v1=001101000010011000001000010001100101001101110011011100000011010000011000001000010010001001110110011111010100100001110000001111100000101100110110010111110110101101000010000111110101011001101110010000010011001001000110011100000111110000101110001100000011010101110001010110100100100000010000&v2=01010100001010110011010101111111000111110110000000000010001100110110000101001111001010110110001100001001011110110001100100100010011010100010100001110101&pl=CommandSpy
[02:25:49 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
[02:25:49 WARN]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[02:25:49 WARN]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[02:25:49 WARN]: 	at java.net.URL.openStream(URL.java:1067)
[02:25:49 WARN]: 	at co.uk.joshuahagon.web.Metrics_Alternate.addMetric(Metrics_Alternate.java:18)
[02:25:49 WARN]: 	at co.uk.joshuahagon.plugin.commandspy.CraftBukkit.onEnable(CraftBukkit.java:19)
[02:25:49 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[02:25:49 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[02:25:49 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[02:25:49 WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[02:25:49 WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[02:25:49 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[02:25:49 WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[02:25:49 WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876)
[02:25:49 WARN]: 	at java.lang.Thread.run(Thread.java:748)
`
